### PR TITLE
Add not-shown tooltip

### LINKED ISSUE #142: Records that display in the middle of the ocean should not be hidden
Records that display in the middle of the ocean should not be hidden, rather a single point with the number of records should be visible. Upon clicking the record, either one of the following should happen:

**Option A:** You are immediately switched to the “Table” view, and the results in the table are all of the records contained in the dot you just clicked on. If you hover over it, a plain browser tooltip displays something like “123 records, of scope global”

**Option B:** Leaflet/jQuery tooltip appears, explaining that there are x number of records here, and a hyperlink appears that you can then click on to be transported to the Table view, where you see the same results as Option A.

### PR DESCRIPTION
**Pull request by jackharrhy**
Resolves #142 

## What

Adds a new marker to a spot in the center of the map (not `null` island but close!) that once clicked on opens up a popup box that tells the user that other items can be found in the table, only if there are items to actually be hidden.

image

---

Tasks left:

- Icon: @ecumene-software can hopefully do up a icon to represent this _other_ marker?
- Ensure that on map reload the old marker is destroyed.

### CODE REVIEW

**Review by ranguli — CHANGES_REQUESTED** [review]
The styling is a little all over the place compared to what the tooltip styles are supposed to look like (see screenshot)

If you can, change the text to be the correct size for a tooltip, and instead of a button, follow the same style of having a hyperlink in the bottom left corner (in the screenshot, "Details") but instead it can have something like "Show in table" etc.

This way we're following the same style guide that the original devs have put in place.

tooltip

**Comment by jackharrhy** [comment]
Yeah I wasn't happy with the style of it either, I just wanted to get the implementation out and then clean it up afterwards, I forgot the tooltip is also used for that so I'll implement that instead :+1:

**Comment by jackharrhy** [comment]
image

**Comment by jackharrhy** [comment]
Change icon to triangles, use location of where items are found.

**Comment by jackharrhy** [comment]
@ranguli changes made

**Comment by jackharrhy** [comment]
image
Should look like this

**Review by nint8835 — APPROVED** [review]
🗺 🤷‍♂️

**Review by ranguli — APPROVED** [review]

**Pull request merged**
