### PR TITLE
JS Dependency updates and CDN changes

### PR DESCRIPTION
**Pull request by ecumene**
Updated to JQuery 3, changed a CDN to cloudflare, ect.

### CODE REVIEW

**Review by nint8835 — APPROVED** [review]
🚀 🏎 ✈️ 🚤 👍  👍  👍  👍  👍  👍  👍

**Comment by ecumene** [comment]
Possibly causes map issues?

**Comment by jackharrhy** [comment]
Map issues seem to be only coming from this branch, would not recommend merging until we get to the root of this problem.

**Comment by jackharrhy** [comment]
Unable to reproduce previous error, potentially an issue with the map connectivity at the time of testing.

**Review by jackharrhy — APPROVED** [review]

**Pull request merged**
