### PR TITLE
Add PDF generation abilities

### PR DESCRIPTION
**Pull request by nint8835**
Adds a new route, /details/report-pdf, that functions the same as /details/report, but instead generates a PDF of the report, complete with things such as unfilled headers to reduce wasted ink (thanks @jackharrhy!)

Example:

### CODE REVIEW

**Comment by ranguli** [comment]
Awesome. Can we hold off on merging until we get the chart size figured out?

**Comment by jackharrhy** [comment]
Almost done the frontend implementation

**Comment by jackharrhy** [comment]
selection_003

Download button finished

**Comment by jackharrhy** [comment]
:star:

**Review by jackharrhy — APPROVED** [review]

**Pull request merged**
