### PR TITLE
Hide Global and Not specific SSFs from the map

### LINKED ISSUE #2: Records with no geographic scope of "Not specific"show up on the map in the middle of the ocean
As seen in the picture below, records that have a geographic scope of "Not specific" show up in the middle of the ocean.

Currently open to suggestions as to how this should be resolved (i.e should these records be hidden on the map altogether, only showing up in the table?)

points

### PR DESCRIPTION
**Pull request by jackharrhy**
Fixes #2 

issf__information_system_on_small-scale_fisheries

### CODE REVIEW

**Comment by jackharrhy** [comment]
Not implemented: some sort of graphic way of showing how many are hidden, although that value is stored within `notShown`, so implementation would just be a graphical thing and not a addition to the underlying javascript.

**Review by ranguli — CHANGES_REQUESTED** [review]
Can we get the functionality for how many records are implemented? It can probably be on the same line (or next to) the text "Current Search Terms: None (showing all 2920 records)" beneath the search bar.

**Comment by ecumene** [comment]
Looks good to me, should I start an issue for the not shown graphic?

**Comment by ranguli** [comment]
Yeah, go ahead @ecumene-software. It should probably be updated to "(showing x records, y records hidden)" instead of "(showing all 2920 records)"

**Comment by jackharrhy** [comment]
> Yeah, go ahead @ecumene-software. It should probably be updated to "(showing x records, y records hidden)" instead of "(showing all 2920 records)"

7eb5937

**Pull request merged**
